### ISSUE TITLE
Revisar el diagrama uml

### ISSUE THREAD

**Issue by yilianmarian** [yilianmarian/Proyecto-de-VP#7]

**Comment by yosbel-penate** [comment]
Esta bien para una primera iteración, solo que algunas relaciones fuertes están demás, para quenexista una relación fuerte la existencia del objeto superior debe depender de la existencia de los objetos inferiores. Si desaparece el último de los objetos inferiores debe desaparecer el superior? Es la pregunta que nos hacemos cuando tenemos duda del tipo de relación que es
